In [31]:
import pandas as pd
from scipy import stats

In [32]:
data = pd.read_csv("results/all_datasets_results.csv")

In [33]:
data = pd.read_csv('results/all_datasets_results.csv')
i = 0
for dataset_name in ['digits', 'ml_multiclass_classification_data', 'otto', 'crop', 'glass', 'isolet']:
    data1 = data[data['dataset'] == dataset_name]
    A_type = ['random_features', 'fisher', 'relief', 'Chi_square']
    B_type = ['hellinger_rank', 'hellinger_kmeans',
       'hellinger_kmediods', 'hellinger_distance_from_0', 'jm_rank',
       'jm_kmeans', 'jm_kmediods', 'jm_distance_from_0', 'wasserstein_rank',
       'wasserstein_kmeans', 'wasserstein_kmediods',
       'wasserstein_distance_from_0']
    df = pd.DataFrame(data={'dataset': [dataset_name]})
    for a in A_type:
        for b in B_type:
            # t test is A>B
            df[a + ' ' + b] = stats.ttest_rel(data1[a], data1[b], alternative='less')[1]
    if i>0:
        old_df = pd.read_csv('t_test_results.csv')
        df = pd.concat([df, old_df], ignore_index=True)
        
    df.to_csv('t_test_results.csv')
    i += 1

In [34]:
df

,dataset,random_features hellinger_rank,random_features hellinger_kmeans,random_features hellinger_kmediods,random_features hellinger_distance_from_0,random_features jm_rank,random_features jm_kmeans,random_features jm_kmediods,random_features jm_distance_from_0,random_features wasserstein_rank,...,Chi_square jm_distance_from_0,Chi_square wasserstein_rank,Chi_square wasserstein_kmeans,Chi_square wasserstein_kmediods,Chi_square wasserstein_distance_from_0,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1
0,isolet,1.000000,1.000000e+00,1.807746e-07,0.999999,0.999999,6.492762e-01,1.000000,1.000000e+00,1.000000,...,1.301355e-31,9.999931e-01,3.873467e-33,3.223466e-24,7.295854e-50,NaN,NaN,NaN,NaN,NaN
1,glass,0.000540,9.999824e-01,7.793881e-01,0.973961,0.998389,9.999943e-01,0.846316,6.706964e-01,0.995245,...,3.577099e-01,9.851807e-01,8.237568e-07,9.805915e-01,3.196085e-03,0.0,NaN,NaN,NaN,NaN
2,crop,0.999999,1.000000e+00,5.009484e-05,1.000000,0.999975,6.499480e-10,0.608389,1.000000e+00,0.999776,...,1.000000e+00,9.999883e-01,2.976462e-01,1.000000e+00,1.000000e+00,1.0,0.0,NaN,NaN,NaN
3,otto,0.951639,3.967758e-07,8.820517e-01,0.324074,0.241139,9.979747e-01,0.024129,9.999101e-01,1.000000,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.0,1.0,0.0,NaN,NaN
4,ml_multiclass_classification_data,1.000000,9.922644e-06,9.407251e-01,1.000000,1.000000,2.365340e-05,0.959151,1.000000e+00,1.000000,...,2.378538e-24,1.645226e-21,8.350824e-33,4.364989e-25,3.130861e-23,3.0,2.0,1.0,0.0,NaN
5,digits,0.999985,1.000000e+00,3.233365e-08,0.999733,0.999998,3.438498e-14,1.000000,6.405719e-07,0.992249,...,8.523463e-30,8.715698e-01,3.078750e-27,1.325138e-27,9.988768e-01,4.0,3.0,2.0,1.0,0.0

In [14]:
B_type

Index(['relief', 'Chi_square', 'hellinger_rank', 'hellinger_kmeans',
       'hellinger_kmediods', 'hellinger_distance_from_0', 'jm_rank',
       'jm_kmeans', 'jm_kmediods', 'jm_distance_from_0', 'wasserstein_rank',
       'wasserstein_kmeans', 'wasserstein_kmediods',
       'wasserstein_distance_from_0'],
      dtype='object')

In [50]:
A_type = ['random_features','fisher','relief','Chi_square']
B_type = data.iloc[:,8:].columns

In [51]:
df = pd.DataFrame(data={'dataset': [dataset]})

In [52]:
for a in A_type:
    for b in B_type:
        df[a+' '+b] = stats.ttest_ind(data[a],data[b], alternative ='less')[1]

In [53]:
old_df =  pd.read_csv('t_test_results.csv')

In [54]:
old_df

,Unnamed: 0,dataset,random_features hellinger_rank,random_features hellinger_kmeans,random_features hellinger_kmediods,random_features hellinger_distance_from_0,random_features jm_rank,random_features jm_kmeans,random_features jm_kmediods,random_features jm_distance_from_0,...,Chi_square hellinger_kmediods,Chi_square hellinger_distance_from_0,Chi_square jm_rank,Chi_square jm_kmeans,Chi_square jm_kmediods,Chi_square jm_distance_from_0,Chi_square wasserstein_rank,Chi_square wasserstein_kmeans,Chi_square wasserstein_kmediods,Chi_square wasserstein_distance_from_0
0,0,spambase,0.472913,0.389426,0.238774,0.471889,0.509563,0.340027,0.392522,0.697496,...,0.943255,0.973176,0.961456,0.944928,0.943038,0.960838,0.981001,0.895304,0.953514,0.937717

In [55]:
df

,dataset,random_features hellinger_rank,random_features hellinger_kmeans,random_features hellinger_kmediods,random_features hellinger_distance_from_0,random_features jm_rank,random_features jm_kmeans,random_features jm_kmediods,random_features jm_distance_from_0,random_features wasserstein_rank,...,Chi_square hellinger_kmediods,Chi_square hellinger_distance_from_0,Chi_square jm_rank,Chi_square jm_kmeans,Chi_square jm_kmediods,Chi_square jm_distance_from_0,Chi_square wasserstein_rank,Chi_square wasserstein_kmeans,Chi_square wasserstein_kmediods,Chi_square wasserstein_distance_from_0
0,glass,0.200032,0.434975,0.320436,0.29731,0.22223,0.432627,0.246554,0.222885,0.195542,...,0.518014,0.469882,0.378173,0.657133,0.412141,0.373243,0.338573,0.271943,0.651185,0.194213

In [56]:
df = df.append(old_df)

In [57]:
df

,dataset,random_features hellinger_rank,random_features hellinger_kmeans,random_features hellinger_kmediods,random_features hellinger_distance_from_0,random_features jm_rank,random_features jm_kmeans,random_features jm_kmediods,random_features jm_distance_from_0,random_features wasserstein_rank,...,Chi_square hellinger_distance_from_0,Chi_square jm_rank,Chi_square jm_kmeans,Chi_square jm_kmediods,Chi_square jm_distance_from_0,Chi_square wasserstein_rank,Chi_square wasserstein_kmeans,Chi_square wasserstein_kmediods,Chi_square wasserstein_distance_from_0,Unnamed: 0
0,glass,0.200032,0.434975,0.320436,0.297310,0.222230,0.432627,0.246554,0.222885,0.195542,...,0.469882,0.378173,0.657133,0.412141,0.373243,0.338573,0.271943,0.651185,0.194213,NaN
0,spambase,0.472913,0.389426,0.238774,0.471889,0.509563,0.340027,0.392522,0.697496,0.723770,...,0.973176,0.961456,0.944928,0.943038,0.960838,0.981001,0.895304,0.953514,0.937717,0.0